[pytest]
testpaths = src/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -p no:cacheprovider --tb=short -q
norecursedirs = __pycache__
collect_ignore_glob = src/tests/old/*